FROM harbor-b.alauda.cn/devops/golang:1.15-custom

ADD .   /go/src/github.com/aquasecurity/harbor-scanner-trivy/
WORKDIR /go/src/github.com/aquasecurity/harbor-scanner-trivy/

RUN export GOOS=linux GO111MODULE=on CGO_ENABLED=0 && \
	go build -buildmode=pie -ldflags "-w -s -linkmode=external -extldflags=-Wl,-z,relro,-z,now" -o scanner-trivy cmd/scanner-trivy/main.go
