FROM golang:1.19.4

ADD .   /go/src/github.com/aquasecurity/harbor-scanner-trivy/
WORKDIR /go/src/github.com/aquasecurity/harbor-scanner-trivy/

RUN export GOOS=linux GO111MODULE=on CGO_ENABLED=0 && \
	go get golang.org/x/net@v0.33.0 && \
	go build --ldflags "-w -s -extldflags '-static'" -o scanner-trivy cmd/scanner-trivy/main.go
