FROM docker-mirrors.alauda.cn/library/golang:1.24.4

ADD .   /go/src/github.com/aquasecurity/trivy/
WORKDIR /go/src/github.com/aquasecurity/trivy/

RUN set -ex && export GOPROXY='https://build-nexus.alauda.cn/repository/golang/,direct' GOOS=linux GO111MODULE=on CGO_ENABLED=0 && \
	go get github.com/go-viper/mapstructure/v2@v2.3.0 && \
	go mod tidy && \
	export GOMAXPROCS=4 && \
	go build --ldflags "-w -s -extldflags '-static'" -o trivy cmd/trivy/main.go
