FROM build-harbor.alauda.cn/ops/photon:4

RUN tdnf install -y rpm shadow >> /dev/null \
    && tdnf clean all \
    && groupadd -r -g 10000 scanner \
    && useradd --no-log-init -m -r -g 10000 -u 10000 scanner
