FROM photon:5.0

RUN tdnf makecache && tdnf install -y cronie rsyslog logrotate shadow tar gzip sudo >> /dev/null\
    && mkdir /var/spool/rsyslog \
    && groupadd -r -g 10000 syslog && useradd -s /sbin/nologin --no-log-init -r -g 10000 -u 10000 syslog \
    && tdnf clean all \
    && chage -M 99999 root
