FROM harbor-b.alauda.cn/ops/photon:4.0

RUN tdnf install sudo tzdata -y >> /dev/null \
    && tdnf clean all \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -r -m -g 10000 -u 10000 harbor
