FROM build-harbor.alauda.cn/ops/ubuntu:22.04 as tool_builder
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8
WORKDIR /tool

ARG ARCH=amd64

#RUN tdnf install -y \
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    git \
    tar \
    #go
    #ubuntu
    curl \
    libssl-dev \
    uuid-dev
#ubuntu
RUN apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:longsleep/golang-backports && \
    apt-get install -y golang-go

RUN pwd && mkdir /tool/binary && \
    # Install CONTAINERD
    CONTAINERD_VERSION=1.7.20 &&  \
    wget https://github.com/containerd/containerd/releases/download/v$CONTAINERD_VERSION/containerd-$CONTAINERD_VERSION-linux-${ARCH}.tar.gz && \
    tar zxvf containerd-$CONTAINERD_VERSION-linux-${ARCH}.tar.gz && \
    cd bin && cp -f containerd ctr /tool/binary/ && \
    # docker compose
    curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /tool/binary/docker-compose && \
    chmod +x /tool/binary/docker-compose && \
    # Install helm
    HELM_VERSION=3.15.3 && wget https://get.helm.sh/helm-v$HELM_VERSION-linux-${ARCH}.tar.gz && \
    tar zxvf helm-v$HELM_VERSION-linux-${ARCH}.tar.gz && \
    ls || pwd && \
    mv linux-${ARCH}/helm /tool/binary/helm && \
    # Install ORAS
    ORAS_VERSION=1.2.0 && curl -LO https://github.com/deislabs/oras/releases/download/v$ORAS_VERSION/oras_${ORAS_VERSION}_linux_${ARCH}.tar.gz && \
    mkdir -p oras-install/  && \
    tar -zxf oras_${ORAS_VERSION}_*.tar.gz -C oras-install/  && \
    mv oras-install/oras /tool/binary/ && \
    # Install CNAB
    CNAB_PATH=$(go env GOPATH)/src/github.com/cnabio && \
    mkdir -p $CNAB_PATH && cd $CNAB_PATH && git clone https://github.com/cnabio/cnab-to-oci.git && \
    cd cnab-to-oci && git checkout v0.4.0 && \
    go list && \
    make build && \
    mv bin/cnab-to-oci /tool/binary/ && \
    # Install DIND
    DIND_COMMIT=3b5fac462d21ca164b3778647420016315289034 && \
    wget "https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind" -O /tool/binary/dind \
    && chmod +x /tool/binary/dind && \
    # Install imgpkg
    IMGPKG_VERSION=0.43.0 && wget https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v$IMGPKG_VERSION/imgpkg-linux-${ARCH} && \
    mv imgpkg-linux-${ARCH} /tool/binary/imgpkg && chmod +x /tool/binary/imgpkg && \
    # Install cosign
    COSIGN_VERSION=2.4.0 && wget https://github.com/sigstore/cosign/releases/download/v$COSIGN_VERSION/cosign-linux-${ARCH} && \
    mv cosign-linux-${ARCH} /tool/binary/cosign && chmod +x /tool/binary/cosign && \
    # # Install notation
    NOTATION_VERSION=1.1.1 && wget https://github.com/notaryproject/notation/releases/download/v$NOTATION_VERSION/notation_${NOTATION_VERSION}_linux_${ARCH}.tar.gz && \
    tar zxvf notation_${NOTATION_VERSION}_linux_${ARCH}.tar.gz && \
    mv notation /tool/binary/notation && chmod +x /tool/binary/notation && \
    pwd

RUN cd /tool/binary/ && tar czvf tools.tar.gz * && cp tools.tar.gz /tool
# --- End of base file ---
