apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 120m
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
  tasks:
    - name: generate-version
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        results:
          - name: commit-short-id
            description: The precise commit short SHA that was fetched by this Task
        steps:
          - name: generate-commit-short-id
            image: build-harbor.alauda.cn/devops/kubectl-devops:master
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              set -ex
              
              # avoid `detected dubious ownership in repository at`
              git config --global --add safe.directory "$(workspaces.source.path)"
              
              RESULT_SHA="$(git rev-parse HEAD)"
              echo -n "${RESULT_SHA:0:8}" >  $(results.commit-short-id.path)
        workspaces:
          - name: source
            workspace: source

    - name: build-image
      runAfter:
        - generate-version
      workspaces:
        - name: source
          workspace: source
      params:
        - name: version
          value: 2.2.3-$(tasks.generate-version.results.commit-short-id)
        - name: components
          value:
            - harbor-portal
            - notary-server-photon
            - notary-signer-photon
            - harbor-registryctl
            - registry-photon
            - nginx-photon
            - harbor-jobservice
            - harbor-core
            - harbor-db
            - chartmuseum-photon
            - trivy-adapter-photon
            - harbor-exporter
        - name: container-images
          value:
            - build-harbor.alauda.cn/devops/docker:19-dind
      taskSpec:
        metadata:
          annotations:
            katanomi.dev/class.ociContainerImageBuild: "true"
        params:
          - name: version
            description: harbor version
          - name: components
            type: array
            description: harbor components list
          - name: container-images
            type: array
            description: used for insert secret
        volumes:
          - name: dind-certs
            emptyDir: {}
        sidecars:
          - image: registry.alauda.cn:60080/devops/docker:19-dind
            name: docker-daemon
            args:
              - --storage-driver=overlay2
              - --userland-proxy=false
              - --debug
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR  # 将生成的证书写入与客户端共享的路径
                value: /certs
              - name: DOCKER_OPTS
                value: "--registry-mirror=https://docker.mirrors.ustc.edu.cn/"
            resources:
              requests:
                cpu: 1000m
                memory: 2000Mi
              limits:
                cpu: 4000m
                memory: 8000Mi
            volumeMounts:
              - mountPath: /certs/client
                name: dind-certs
              - mountPath: /workspace/source
                name: $(workspaces.source.volume)
            readinessProbe: # 等待 dind daemon 生成它与客户端共享的证书
              periodSeconds: 1
              exec:
                command: [ 'ls', '/certs/client/ca.pem' ]
          - image: registry.alauda.cn:60080/test/registry:2.8.1
            name: docker-registry
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 1000m
                memory: 2000Mi
              limits:
                cpu: 4000m
                memory: 8000Mi
        steps:
          - name: build-amd64
            image: registry.alauda.cn:60080/devops/builder-tools:ubuntu-v3.8.1
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.source.path)
            timeout: 120m
            resources:
              requests:
                cpu: 1000m
                memory: 2000Mi
              limits:
                cpu: 2000m
                memory: 4000Mi
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_TLS_VERIFY
                value: '1'
              - name: DOCKER_CERT_PATH
                value: /certs/client
            volumeMounts:
              - mountPath: /certs/client
                name: dind-certs
            script: |
              #!/bin/bash
              set -ex

              git config --global --add safe.directory $(workspaces.source.path)

              bash make/patches/patch-amd64.sh
#
#              BUILDPATH=$(workspaces.source.path)
#              VERSIONTAG=$(params.version)-amd64
#              BASEIMAGETAG=$(params.version)-amd64
#              BASEIMAGENAMESPACE=localhost:5000
#
#              BUILDPATH="$BUILDPATH" make compile
#              BUILDPATH="$BUILDPATH" BASEIMAGETAG="$BASEIMAGETAG" BASEIMAGENAMESPACE="$BASEIMAGENAMESPACE" VERSIONTAG="$VERSIONTAG" make build

          - name: build-arm64
            image: registry.alauda.cn:60080/devops/builder-tools:ubuntu-v3.8.1
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.source.path)
            timeout: 120m
            retries: 2
            resources:
              requests:
                cpu: 1000m
                memory: 2000Mi
              limits:
                cpu: 2000m
                memory: 4000Mi
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_TLS_VERIFY
                value: '1'
              - name: DOCKER_CERT_PATH
                value: /certs/client
            volumeMounts:
              - mountPath: /certs/client
                name: dind-certs
            script: |
              #!/bin/bash
              set -ex

              git config --global --add safe.directory $(workspaces.source.path)

              bash make/patches/patch-arm64.sh

              BUILDPATH=$(workspaces.source.path)
              VERSIONTAG=$(params.version)-arm64
              BASEIMAGETAG=$(params.version)-arm64
              BASEIMAGENAMESPACE=localhost:5000

              BUILDPATH="$BUILDPATH" make compile
              BUILDPATH="$BUILDPATH" BASEIMAGETAG="$BASEIMAGETAG" BASEIMAGENAMESPACE="$BASEIMAGENAMESPACE" VERSIONTAG="$VERSIONTAG" make build

          - name: build-manifests
            image: registry.alauda.cn:60080/devops/builder-tools:ubuntu-v3.8.1
            imagePullPolicy: IfNotPresent
            workingDir: $(workspaces.source.path)
            timeout: 120m
            retries: 2
            resources:
              requests:
                cpu: 1000m
                memory: 2000Mi
              limits:
                cpu: 2000m
                memory: 4000Mi
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_TLS_VERIFY
                value: '1'
              - name: DOCKER_CERT_PATH
                value: /certs/client
            volumeMounts:
              - mountPath: /certs/client
                name: dind-certs
            script: |
              #!/bin/bash
              set -ex
              
              git config --global --add safe.directory $(workspaces.source.path)
              
              VERSIONTAG=$(params.version) bash make/patches/push-images.sh
        workspaces:
          - name: source
            workspace: source




