apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: |
        This workspace is shared among all the pipeline tasks to read/write common resources
      name: source
  tasks:
    - name: prepare-dockerfile
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: alauda-script
      workspaces:
        - name: source
          workspace: source
      params:
        - name: tool-image
          value: registry.alauda.cn:60080/fundamentals/katanomi-ci-builder:master
        - name: script
          value: | 
           cd tests/test-engine-image && ./generate.sh api
    - name: build-image-amd
      timeout: 60m
      retries: 0
      runAfter:
          - prepare-dockerfile
      taskRef:
        kind: ClusterTask
        name: build-image-buildkit
      workspaces:
        - name: source
          workspace: source
        - name: cache
        - name: config
      when: []
      params:
        - name: reuse-image
          value: "false"
        - name: dockerfile
          value: tests/test-engine-image/Dockerfile
        - name: context
          value: tests/test-engine-image
        - name: container-images
          value:
            - build-harbor.alauda.cn/fundamentals/harbor-e2e-engine:4.2.1-api
        - name: labels
          value:
            - branch=$(build.git.branch.name)
            - commit=$(build.git.lastCommit.id)
            - commit_id=$(build.git.lastCommit.id)
