apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  git:
    options:
      depth: 3
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
  workspaces:
    - name: source
  params:
    - name: HARBOR_PASSWORD
      description: 密码
      type: string
      default: Harbor12345
    - name: HARBOR_HOST
      description: harbor 地址，访问地址去掉协议的部分，如 harbor.test、127.0.0.1:8080
      type: string
      default: ""
    - name: HARBOR_HOST_SCHEMA
      description: harbor 地址的协议，http 或者 https
      type: string
      default: "http"
    - name: TEST_IMAGE
      description: 测试镜像的地址
      type: string
      default: "build-harbor.alauda.cn/fundamentals/harbor-e2e-engine:4.2.1-api"
  tasks:
    - name: api-test
      timeout: 2.5h
      retries: 0
      taskRef:
        resolver: katanomi.dev.gitsource
        params:
          - name: url
            value: https://gitlab-ce.alauda.cn/devops/edge
          - name: revision
            value: refs/heads/master
          - name: pathInRepo
            value: tasks/docker-in-docker/0.1/docker-in-docker.yaml
      workspaces:
        - name: source
          workspace: source
      params:
        - name: command
          value: |
            export HARBOR_HOST=$(params.HARBOR_HOST) 
            export HARBOR_HOST_SCHEMA=$(params.HARBOR_HOST_SCHEMA)
            export HARBOR_PASSWORD=$(params.HARBOR_PASSWORD)
            export E2E_IMAGE=$(params.TEST_IMAGE)
            
            ./tests/ci/api_run.sh DB $(params.HARBOR_HOST)

    - name: upload-report
      timeout: 30m
      retries: 0
      runAfter:
        - api-test
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: upload-files
      workspaces:
        - name: source
          workspace: source
      params:
        - name: artifacts-path
          value:
            - $(workspaces.source.path)/log.html
        - name: artifact-repository
          value: https://build-nexus.alauda.cn/repository/alauda/
        - name: target-path
          value: ./devops/pipeline-report/harbor-e2e/$(build.git.branch)/
        - name: checksum
          value: "false"
        - name: upload-pack
          value: "false"