FROM harbor-b.alauda.cn/ops/photon:3.0 AS source

FROM scratch
COPY --from=source / /

RUN groupadd -r -g 10000 harbor && useradd --no-log-init -m -g 10000 -u 10000 harbor \
    && mkdir -p /etc/registry
