FROM harbor-b.alauda.cn/ops/toolbox:1.0 AS tools

FROM harbor-b.alauda.cn/ops/photon:3.0 AS source

COPY --from=tools /opt/bash/lib /opt/bash/lib

RUN mkdir /clair-adapter/ \
    && groupadd -r -g 10000 clair-adapter \
    && useradd --no-log-init -m -r -g 10000 -u 10000 clair-adapter \
    && echo "/opt/bash/lib" >>/etc/ld.so.conf \
    && ldconfig \
    && rm -rf /usr/lib/bash && rm -rf /usr/share/doc/bash

FROM scratch
COPY --from=source / /
