FROM harbor-b.alauda.cn/ops/photon:3.0 AS source

RUN tdnf install nginx -y >> /dev/null\
    && tdnf clean all \
    && groupadd -r -g 10000 nginx && useradd --no-log-init -r -g 10000 -u 10000 nginx \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

FROM scratch
COPY --from=source / /
