FROM photon:4.0

RUN tdnf install -y shadow &&  groupadd -r -g 10000 nginx && useradd -s /sbin/nologin --no-log-init -r -g 10000 -u 10000 nginx \
    && tdnf  install -y nginx >> /dev/null \
    && tdnf clean all \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log
