FROM harbor-b.alauda.cn/devops/golang:1.15-custom

ADD .   /go/src/github.com/quay/clair/
WORKDIR /go/src/github.com/quay/clair/

RUN export CLAIR_VERSION=$(git describe --tag --always --dirty) GO111MODULE=on && \
	go build -buildmode=pie -ldflags "-w -s -linkmode=external -extldflags=-Wl,-z,relro,-z,now -X github.com/quay/clair/pkg/version.Version=$CLAIR_VERSION" ./cmd/clair
